### ISSUE TITLE
Catagorical variables assignment

### ISSUE THREAD

**Issue by adyasha95** [anaston/cca_pls_toolkit#13]
We couldn't find any information on whether the toolbox allows for categorical variables to be included as features in the SPLS data matrices. We plan to use diagnostic category as a feature (we have multiple diagnoses), rather than as an exchangeability block variable. Is this implemented and how can it be specified?

**Comment by anaston** [comment]
Thanks for raising this issue. CCA/PLS works better with continuous variables but you can also include categorical variables in the model. You should one-hot encode the categorical variables and it’s ok to have as many features as categories e.g., 3 features for 3 diagnostic categories as the dependencies between the variables are taken care of in the toolkit. There is a specific case which should be avoided though. This occurs when a categorical variable has 2 levels and SPLS selects only these 2 in the model. This could also happen if you have only 2 diagnostic categories in one of your data modalities (i.e., Y includes 2 columns). In that case, SPLS will not converge and return NaN weights. If that happens, you should re-code this categorical variable as 1 feature and re-run the analysis.
