### ISSUE TITLE
Including sparsity or PCA for only X

### ISSUE THREAD

**Issue by pauldhami** [anaston/cca_pls_toolkit#17]
Greetings,

Firstly, thank you for the wonderful toolbox. 

I was just curious as to how can I go about having regularization or PCA applied only to my X (biology data), and not Y (clinical data) when working with the CCA frameworks provided. 

For scca, I believe these paremters are doing that?:
```
cfg.machine.param.name = {'L2x', 'L2y'};
cfg.machine.param.L2y = 0; % just apply regularization to X
```

But I am having trouble figuring out how to only apply PCA to X and not Y with the cfg parameters.

Any help would be greatly appreciated.
Thank you!

**Comment by anaston** [comment]
Hi @pauldhami,

Thanks, I hope you will find the toolbox useful.

In case of SPLS, the setting is indeed as you mentioned above.

In case of PCA-CCA, the setting is:
```
cfg.machine.name = 'cca';
cfg.machine.param.name = {'PCAx',  'PCAy'};
cfg.machine.param.PCAy = Inf;
```

Or you could also set `cfg.machine.param.PCAy` to any number that is equal or greater than the number of features in your Y data.

If you use train/test splitting or deconfounding within the toolbox with these settings, then you will get a warning about the number of principal components but you can just safely ignore that.

Best,
Agoston
